export const RESERVED_USERNAMES = new Set([
  "admin",
  "administrator",
  "support",
  "help",
  "benifonla",
  "api",
  "auth",
  "login",
  "register",
  "signup",
  "signin",
  "settings",
  "profile",
  "dashboard",
  "root",
  "system",
  "info",
  "contact",
  "about",
  "faq",
  "terms",
  "privacy",
  "creator",
  "creators",
  "campaign",
  "campaigns",
  "discover",
  "search",
  "me",
  "user",
  "users",
  "null",
  "undefined",
]);

export function isReservedUsername(username: string): boolean {
  return RESERVED_USERNAMES.has(username.toLowerCase());
}
