import type { SupportedSummaryLanguage } from "./languages";

/**
 * Server-managed disclaimer text (per language) attached to every summary
 * response. We do NOT trust the model to produce a stable disclaimer.
 */
export const SUMMARY_DISCLAIMER: Record<SupportedSummaryLanguage, string> = {
  tr:
    "Bu özet yapay zekâ tarafından kampanya içeriği kullanılarak oluşturulmuştur. " +
    "Eksik veya hatalı bilgiler içerebilir. Destek vermeden önce kampanyanın tüm " +
    "açıklamalarını, risklerini, ödül koşullarını ve diğer ayrıntılarını inceleyin. " +
    "Bu özet finansal, hukuki veya yatırım tavsiyesi değildir.",
  en:
    "This summary was generated by AI from the campaign content. It may contain " +
    "missing or inaccurate information. Before supporting the campaign, review " +
    "all original descriptions, risks, reward terms and other details. This " +
    "summary is not financial, legal or investment advice.",
};
