/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProhibitedCampaignsRouteImport } from './routes/prohibited-campaigns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CreatorAgreementRouteImport } from './routes/creator-agreement'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsAndAppealsRouteImport } from './routes/complaints-and-appeals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorsUsernameRouteImport } from './routes/creators.$username'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CampaignsSlugIndexRouteImport } from './routes/campaigns.$slug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedCreatorIndexRouteImport } from './routes/_authenticated/creator.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CampaignsSlugBackRouteImport } from './routes/campaigns.$slug.back'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedDashboardRewardsRouteImport } from './routes/_authenticated/dashboard.rewards'
import { Route as AuthenticatedDashboardRefundsRouteImport } from './routes/_authenticated/dashboard.refunds'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard.favorites'
import { Route as AuthenticatedDashboardContributionsRouteImport } from './routes/_authenticated/dashboard.contributions'
import { Route as AuthenticatedCreatorPaymentAccountRouteImport } from './routes/_authenticated/creator.payment-account'
import { Route as AuthenticatedCreatorCampaignsRouteImport } from './routes/_authenticated/creator.campaigns'
import { Route as AuthenticatedAdminSystemAlertsRouteImport } from './routes/_authenticated/admin.system-alerts'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as CampaignsSlugBackIndexRouteImport } from './routes/campaigns.$slug.back.index'
import { Route as AuthenticatedCreatorCampaignsIndexRouteImport } from './routes/_authenticated/creator.campaigns.index'
import { Route as AuthenticatedAdminCampaignReviewsIndexRouteImport } from './routes/_authenticated/admin.campaign-reviews.index'
import { Route as CampaignsSlugBackRewardRouteImport } from './routes/campaigns.$slug.back.reward'
import { Route as CampaignsSlugBackReviewRouteImport } from './routes/campaigns.$slug.back.review'
import { Route as CampaignsSlugBackResultRouteImport } from './routes/campaigns.$slug.back.result'
import { Route as CampaignsSlugBackDetailsRouteImport } from './routes/campaigns.$slug.back.details'
import { Route as ApiPublicHooksStripeWebhookRouteImport } from './routes/api/public/hooks/stripe-webhook'
import { Route as ApiPublicHooksStripeConnectWebhookRouteImport } from './routes/api/public/hooks/stripe-connect-webhook'
import { Route as ApiPublicHooksRunPaymentReconciliationRouteImport } from './routes/api/public/hooks/run-payment-reconciliation'
import { Route as ApiPublicHooksPublishDueCampaignsRouteImport } from './routes/api/public/hooks/publish-due-campaigns'
import { Route as ApiPublicHooksProcessNotificationOutboxRouteImport } from './routes/api/public/hooks/process-notification-outbox'
import { Route as ApiPublicAiGenerateCampaignSummaryRouteImport } from './routes/api/public/ai/generate-campaign-summary'
import { Route as ApiPublicAiChatRouteImport } from './routes/api/public/ai/chat'
import { Route as AuthenticatedCreatorCampaignsNewRouteImport } from './routes/_authenticated/creator.campaigns.new'
import { Route as AuthenticatedAdminCampaignReviewsCampaignIdRouteImport } from './routes/_authenticated/admin.campaign-reviews.$campaignId'
import { Route as AuthenticatedCreatorCampaignsCampaignIdUpdatesRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.updates'
import { Route as AuthenticatedCreatorCampaignsCampaignIdReviewRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.review'
import { Route as AuthenticatedCreatorCampaignsCampaignIdPreviewRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.preview'
import { Route as AuthenticatedCreatorCampaignsCampaignIdOverviewRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.overview'
import { Route as AuthenticatedCreatorCampaignsCampaignIdFinanceRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.finance'
import { Route as AuthenticatedCreatorCampaignsCampaignIdBackersRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.backers'
import { Route as AuthenticatedCreatorCampaignsCampaignIdAnalyticsRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.analytics'
import { Route as AuthenticatedAdminCampaignsCampaignIdHistoryRouteImport } from './routes/_authenticated/admin.campaigns.$campaignId.history'
import { Route as AuthenticatedCreatorCampaignsCampaignIdEditStepRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.edit.$step'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibitedCampaignsRoute = ProhibitedCampaignsRouteImport.update({
  id: '/prohibited-campaigns',
  path: '/prohibited-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAgreementRoute = CreatorAgreementRouteImport.update({
  id: '/creator-agreement',
  path: '/creator-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsAndAppealsRoute = ComplaintsAndAppealsRouteImport.update({
  id: '/complaints-and-appeals',
  path: '/complaints-and-appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsUsernameRoute = CreatorsUsernameRouteImport.update({
  id: '/creators/$username',
  path: '/creators/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CampaignsSlugIndexRoute = CampaignsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorIndexRoute =
  AuthenticatedCreatorIndexRouteImport.update({
    id: '/creator/',
    path: '/creator/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CampaignsSlugBackRoute = CampaignsSlugBackRouteImport.update({
  id: '/back',
  path: '/back',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedDashboardRewardsRoute =
  AuthenticatedDashboardRewardsRouteImport.update({
    id: '/dashboard/rewards',
    path: '/dashboard/rewards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRefundsRoute =
  AuthenticatedDashboardRefundsRouteImport.update({
    id: '/dashboard/refunds',
    path: '/dashboard/refunds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/dashboard/payments',
    path: '/dashboard/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/dashboard/favorites',
    path: '/dashboard/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardContributionsRoute =
  AuthenticatedDashboardContributionsRouteImport.update({
    id: '/dashboard/contributions',
    path: '/dashboard/contributions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorPaymentAccountRoute =
  AuthenticatedCreatorPaymentAccountRouteImport.update({
    id: '/creator/payment-account',
    path: '/creator/payment-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorCampaignsRoute =
  AuthenticatedCreatorCampaignsRouteImport.update({
    id: '/creator/campaigns',
    path: '/creator/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSystemAlertsRoute =
  AuthenticatedAdminSystemAlertsRouteImport.update({
    id: '/system-alerts',
    path: '/system-alerts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CampaignsSlugBackIndexRoute = CampaignsSlugBackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugBackRoute,
} as any)
const AuthenticatedCreatorCampaignsIndexRoute =
  AuthenticatedCreatorCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedAdminCampaignReviewsIndexRoute =
  AuthenticatedAdminCampaignReviewsIndexRouteImport.update({
    id: '/campaign-reviews/',
    path: '/campaign-reviews/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CampaignsSlugBackRewardRoute = CampaignsSlugBackRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => CampaignsSlugBackRoute,
} as any)
const CampaignsSlugBackReviewRoute = CampaignsSlugBackReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CampaignsSlugBackRoute,
} as any)
const CampaignsSlugBackResultRoute = CampaignsSlugBackResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => CampaignsSlugBackRoute,
} as any)
const CampaignsSlugBackDetailsRoute =
  CampaignsSlugBackDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => CampaignsSlugBackRoute,
  } as any)
const ApiPublicHooksStripeWebhookRoute =
  ApiPublicHooksStripeWebhookRouteImport.update({
    id: '/api/public/hooks/stripe-webhook',
    path: '/api/public/hooks/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeConnectWebhookRoute =
  ApiPublicHooksStripeConnectWebhookRouteImport.update({
    id: '/api/public/hooks/stripe-connect-webhook',
    path: '/api/public/hooks/stripe-connect-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunPaymentReconciliationRoute =
  ApiPublicHooksRunPaymentReconciliationRouteImport.update({
    id: '/api/public/hooks/run-payment-reconciliation',
    path: '/api/public/hooks/run-payment-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishDueCampaignsRoute =
  ApiPublicHooksPublishDueCampaignsRouteImport.update({
    id: '/api/public/hooks/publish-due-campaigns',
    path: '/api/public/hooks/publish-due-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessNotificationOutboxRoute =
  ApiPublicHooksProcessNotificationOutboxRouteImport.update({
    id: '/api/public/hooks/process-notification-outbox',
    path: '/api/public/hooks/process-notification-outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiGenerateCampaignSummaryRoute =
  ApiPublicAiGenerateCampaignSummaryRouteImport.update({
    id: '/api/public/ai/generate-campaign-summary',
    path: '/api/public/ai/generate-campaign-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAiChatRoute = ApiPublicAiChatRouteImport.update({
  id: '/api/public/ai/chat',
  path: '/api/public/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreatorCampaignsNewRoute =
  AuthenticatedCreatorCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedAdminCampaignReviewsCampaignIdRoute =
  AuthenticatedAdminCampaignReviewsCampaignIdRouteImport.update({
    id: '/campaign-reviews/$campaignId',
    path: '/campaign-reviews/$campaignId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute =
  AuthenticatedCreatorCampaignsCampaignIdUpdatesRouteImport.update({
    id: '/$campaignId/updates',
    path: '/$campaignId/updates',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdReviewRoute =
  AuthenticatedCreatorCampaignsCampaignIdReviewRouteImport.update({
    id: '/$campaignId/review',
    path: '/$campaignId/review',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdPreviewRoute =
  AuthenticatedCreatorCampaignsCampaignIdPreviewRouteImport.update({
    id: '/$campaignId/preview',
    path: '/$campaignId/preview',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdOverviewRoute =
  AuthenticatedCreatorCampaignsCampaignIdOverviewRouteImport.update({
    id: '/$campaignId/overview',
    path: '/$campaignId/overview',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdFinanceRoute =
  AuthenticatedCreatorCampaignsCampaignIdFinanceRouteImport.update({
    id: '/$campaignId/finance',
    path: '/$campaignId/finance',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdBackersRoute =
  AuthenticatedCreatorCampaignsCampaignIdBackersRouteImport.update({
    id: '/$campaignId/backers',
    path: '/$campaignId/backers',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute =
  AuthenticatedCreatorCampaignsCampaignIdAnalyticsRouteImport.update({
    id: '/$campaignId/analytics',
    path: '/$campaignId/analytics',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedAdminCampaignsCampaignIdHistoryRoute =
  AuthenticatedAdminCampaignsCampaignIdHistoryRouteImport.update({
    id: '/campaigns/$campaignId/history',
    path: '/campaigns/$campaignId/history',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdEditStepRoute =
  AuthenticatedCreatorCampaignsCampaignIdEditStepRouteImport.update({
    id: '/$campaignId/edit/$step',
    path: '/$campaignId/edit/$step',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/complaints-and-appeals': typeof ComplaintsAndAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/creator-agreement': typeof CreatorAgreementRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-campaigns': typeof ProhibitedCampaignsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/system-alerts': typeof AuthenticatedAdminSystemAlertsRoute
  '/creator/campaigns': typeof AuthenticatedCreatorCampaignsRouteWithChildren
  '/creator/payment-account': typeof AuthenticatedCreatorPaymentAccountRoute
  '/dashboard/contributions': typeof AuthenticatedDashboardContributionsRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/refunds': typeof AuthenticatedDashboardRefundsRoute
  '/dashboard/rewards': typeof AuthenticatedDashboardRewardsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/campaigns/$slug/back': typeof CampaignsSlugBackRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/creator/': typeof AuthenticatedCreatorIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
  '/admin/campaign-reviews/$campaignId': typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  '/creator/campaigns/new': typeof AuthenticatedCreatorCampaignsNewRoute
  '/api/public/ai/chat': typeof ApiPublicAiChatRoute
  '/api/public/ai/generate-campaign-summary': typeof ApiPublicAiGenerateCampaignSummaryRoute
  '/api/public/hooks/process-notification-outbox': typeof ApiPublicHooksProcessNotificationOutboxRoute
  '/api/public/hooks/publish-due-campaigns': typeof ApiPublicHooksPublishDueCampaignsRoute
  '/api/public/hooks/run-payment-reconciliation': typeof ApiPublicHooksRunPaymentReconciliationRoute
  '/api/public/hooks/stripe-connect-webhook': typeof ApiPublicHooksStripeConnectWebhookRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/campaigns/$slug/back/details': typeof CampaignsSlugBackDetailsRoute
  '/campaigns/$slug/back/result': typeof CampaignsSlugBackResultRoute
  '/campaigns/$slug/back/review': typeof CampaignsSlugBackReviewRoute
  '/campaigns/$slug/back/reward': typeof CampaignsSlugBackRewardRoute
  '/admin/campaign-reviews/': typeof AuthenticatedAdminCampaignReviewsIndexRoute
  '/creator/campaigns/': typeof AuthenticatedCreatorCampaignsIndexRoute
  '/campaigns/$slug/back/': typeof CampaignsSlugBackIndexRoute
  '/admin/campaigns/$campaignId/history': typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
  '/creator/campaigns/$campaignId/analytics': typeof AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute
  '/creator/campaigns/$campaignId/backers': typeof AuthenticatedCreatorCampaignsCampaignIdBackersRoute
  '/creator/campaigns/$campaignId/finance': typeof AuthenticatedCreatorCampaignsCampaignIdFinanceRoute
  '/creator/campaigns/$campaignId/overview': typeof AuthenticatedCreatorCampaignsCampaignIdOverviewRoute
  '/creator/campaigns/$campaignId/preview': typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  '/creator/campaigns/$campaignId/review': typeof AuthenticatedCreatorCampaignsCampaignIdReviewRoute
  '/creator/campaigns/$campaignId/updates': typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  '/creator/campaigns/$campaignId/edit/$step': typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/complaints-and-appeals': typeof ComplaintsAndAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/creator-agreement': typeof CreatorAgreementRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-campaigns': typeof ProhibitedCampaignsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/system-alerts': typeof AuthenticatedAdminSystemAlertsRoute
  '/creator/payment-account': typeof AuthenticatedCreatorPaymentAccountRoute
  '/dashboard/contributions': typeof AuthenticatedDashboardContributionsRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/refunds': typeof AuthenticatedDashboardRefundsRoute
  '/dashboard/rewards': typeof AuthenticatedDashboardRewardsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/creator': typeof AuthenticatedCreatorIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/campaigns/$slug': typeof CampaignsSlugIndexRoute
  '/admin/campaign-reviews/$campaignId': typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  '/creator/campaigns/new': typeof AuthenticatedCreatorCampaignsNewRoute
  '/api/public/ai/chat': typeof ApiPublicAiChatRoute
  '/api/public/ai/generate-campaign-summary': typeof ApiPublicAiGenerateCampaignSummaryRoute
  '/api/public/hooks/process-notification-outbox': typeof ApiPublicHooksProcessNotificationOutboxRoute
  '/api/public/hooks/publish-due-campaigns': typeof ApiPublicHooksPublishDueCampaignsRoute
  '/api/public/hooks/run-payment-reconciliation': typeof ApiPublicHooksRunPaymentReconciliationRoute
  '/api/public/hooks/stripe-connect-webhook': typeof ApiPublicHooksStripeConnectWebhookRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/campaigns/$slug/back/details': typeof CampaignsSlugBackDetailsRoute
  '/campaigns/$slug/back/result': typeof CampaignsSlugBackResultRoute
  '/campaigns/$slug/back/review': typeof CampaignsSlugBackReviewRoute
  '/campaigns/$slug/back/reward': typeof CampaignsSlugBackRewardRoute
  '/admin/campaign-reviews': typeof AuthenticatedAdminCampaignReviewsIndexRoute
  '/creator/campaigns': typeof AuthenticatedCreatorCampaignsIndexRoute
  '/campaigns/$slug/back': typeof CampaignsSlugBackIndexRoute
  '/admin/campaigns/$campaignId/history': typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
  '/creator/campaigns/$campaignId/analytics': typeof AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute
  '/creator/campaigns/$campaignId/backers': typeof AuthenticatedCreatorCampaignsCampaignIdBackersRoute
  '/creator/campaigns/$campaignId/finance': typeof AuthenticatedCreatorCampaignsCampaignIdFinanceRoute
  '/creator/campaigns/$campaignId/overview': typeof AuthenticatedCreatorCampaignsCampaignIdOverviewRoute
  '/creator/campaigns/$campaignId/preview': typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  '/creator/campaigns/$campaignId/review': typeof AuthenticatedCreatorCampaignsCampaignIdReviewRoute
  '/creator/campaigns/$campaignId/updates': typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  '/creator/campaigns/$campaignId/edit/$step': typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/complaints-and-appeals': typeof ComplaintsAndAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/creator-agreement': typeof CreatorAgreementRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/prohibited-campaigns': typeof ProhibitedCampaignsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/system-alerts': typeof AuthenticatedAdminSystemAlertsRoute
  '/_authenticated/creator/campaigns': typeof AuthenticatedCreatorCampaignsRouteWithChildren
  '/_authenticated/creator/payment-account': typeof AuthenticatedCreatorPaymentAccountRoute
  '/_authenticated/dashboard/contributions': typeof AuthenticatedDashboardContributionsRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/refunds': typeof AuthenticatedDashboardRefundsRoute
  '/_authenticated/dashboard/rewards': typeof AuthenticatedDashboardRewardsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/campaigns/$slug/back': typeof CampaignsSlugBackRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/creator/': typeof AuthenticatedCreatorIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
  '/_authenticated/admin/campaign-reviews/$campaignId': typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  '/_authenticated/creator/campaigns/new': typeof AuthenticatedCreatorCampaignsNewRoute
  '/api/public/ai/chat': typeof ApiPublicAiChatRoute
  '/api/public/ai/generate-campaign-summary': typeof ApiPublicAiGenerateCampaignSummaryRoute
  '/api/public/hooks/process-notification-outbox': typeof ApiPublicHooksProcessNotificationOutboxRoute
  '/api/public/hooks/publish-due-campaigns': typeof ApiPublicHooksPublishDueCampaignsRoute
  '/api/public/hooks/run-payment-reconciliation': typeof ApiPublicHooksRunPaymentReconciliationRoute
  '/api/public/hooks/stripe-connect-webhook': typeof ApiPublicHooksStripeConnectWebhookRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/campaigns/$slug/back/details': typeof CampaignsSlugBackDetailsRoute
  '/campaigns/$slug/back/result': typeof CampaignsSlugBackResultRoute
  '/campaigns/$slug/back/review': typeof CampaignsSlugBackReviewRoute
  '/campaigns/$slug/back/reward': typeof CampaignsSlugBackRewardRoute
  '/_authenticated/admin/campaign-reviews/': typeof AuthenticatedAdminCampaignReviewsIndexRoute
  '/_authenticated/creator/campaigns/': typeof AuthenticatedCreatorCampaignsIndexRoute
  '/campaigns/$slug/back/': typeof CampaignsSlugBackIndexRoute
  '/_authenticated/admin/campaigns/$campaignId/history': typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
  '/_authenticated/creator/campaigns/$campaignId/analytics': typeof AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute
  '/_authenticated/creator/campaigns/$campaignId/backers': typeof AuthenticatedCreatorCampaignsCampaignIdBackersRoute
  '/_authenticated/creator/campaigns/$campaignId/finance': typeof AuthenticatedCreatorCampaignsCampaignIdFinanceRoute
  '/_authenticated/creator/campaigns/$campaignId/overview': typeof AuthenticatedCreatorCampaignsCampaignIdOverviewRoute
  '/_authenticated/creator/campaigns/$campaignId/preview': typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  '/_authenticated/creator/campaigns/$campaignId/review': typeof AuthenticatedCreatorCampaignsCampaignIdReviewRoute
  '/_authenticated/creator/campaigns/$campaignId/updates': typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  '/_authenticated/creator/campaigns/$campaignId/edit/$step': typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/complaints-and-appeals'
    | '/contact'
    | '/cookies'
    | '/creator-agreement'
    | '/design-system'
    | '/discover'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/prohibited-campaigns'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/risk-disclosure'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/unauthorized'
    | '/admin'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/campaigns/$slug'
    | '/categories/$slug'
    | '/creators/$username'
    | '/admin/audit'
    | '/admin/system-alerts'
    | '/creator/campaigns'
    | '/creator/payment-account'
    | '/dashboard/contributions'
    | '/dashboard/favorites'
    | '/dashboard/payments'
    | '/dashboard/refunds'
    | '/dashboard/rewards'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/campaigns/$slug/back'
    | '/admin/'
    | '/creator/'
    | '/dashboard/'
    | '/campaigns/$slug/'
    | '/admin/campaign-reviews/$campaignId'
    | '/creator/campaigns/new'
    | '/api/public/ai/chat'
    | '/api/public/ai/generate-campaign-summary'
    | '/api/public/hooks/process-notification-outbox'
    | '/api/public/hooks/publish-due-campaigns'
    | '/api/public/hooks/run-payment-reconciliation'
    | '/api/public/hooks/stripe-connect-webhook'
    | '/api/public/hooks/stripe-webhook'
    | '/campaigns/$slug/back/details'
    | '/campaigns/$slug/back/result'
    | '/campaigns/$slug/back/review'
    | '/campaigns/$slug/back/reward'
    | '/admin/campaign-reviews/'
    | '/creator/campaigns/'
    | '/campaigns/$slug/back/'
    | '/admin/campaigns/$campaignId/history'
    | '/creator/campaigns/$campaignId/analytics'
    | '/creator/campaigns/$campaignId/backers'
    | '/creator/campaigns/$campaignId/finance'
    | '/creator/campaigns/$campaignId/overview'
    | '/creator/campaigns/$campaignId/preview'
    | '/creator/campaigns/$campaignId/review'
    | '/creator/campaigns/$campaignId/updates'
    | '/creator/campaigns/$campaignId/edit/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/complaints-and-appeals'
    | '/contact'
    | '/cookies'
    | '/creator-agreement'
    | '/design-system'
    | '/discover'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/prohibited-campaigns'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/risk-disclosure'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/unauthorized'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/categories/$slug'
    | '/creators/$username'
    | '/admin/audit'
    | '/admin/system-alerts'
    | '/creator/payment-account'
    | '/dashboard/contributions'
    | '/dashboard/favorites'
    | '/dashboard/payments'
    | '/dashboard/refunds'
    | '/dashboard/rewards'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/creator'
    | '/dashboard'
    | '/campaigns/$slug'
    | '/admin/campaign-reviews/$campaignId'
    | '/creator/campaigns/new'
    | '/api/public/ai/chat'
    | '/api/public/ai/generate-campaign-summary'
    | '/api/public/hooks/process-notification-outbox'
    | '/api/public/hooks/publish-due-campaigns'
    | '/api/public/hooks/run-payment-reconciliation'
    | '/api/public/hooks/stripe-connect-webhook'
    | '/api/public/hooks/stripe-webhook'
    | '/campaigns/$slug/back/details'
    | '/campaigns/$slug/back/result'
    | '/campaigns/$slug/back/review'
    | '/campaigns/$slug/back/reward'
    | '/admin/campaign-reviews'
    | '/creator/campaigns'
    | '/campaigns/$slug/back'
    | '/admin/campaigns/$campaignId/history'
    | '/creator/campaigns/$campaignId/analytics'
    | '/creator/campaigns/$campaignId/backers'
    | '/creator/campaigns/$campaignId/finance'
    | '/creator/campaigns/$campaignId/overview'
    | '/creator/campaigns/$campaignId/preview'
    | '/creator/campaigns/$campaignId/review'
    | '/creator/campaigns/$campaignId/updates'
    | '/creator/campaigns/$campaignId/edit/$step'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/complaints-and-appeals'
    | '/contact'
    | '/cookies'
    | '/creator-agreement'
    | '/design-system'
    | '/discover'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/prohibited-campaigns'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/risk-disclosure'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/campaigns/$slug'
    | '/categories/$slug'
    | '/creators/$username'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/system-alerts'
    | '/_authenticated/creator/campaigns'
    | '/_authenticated/creator/payment-account'
    | '/_authenticated/dashboard/contributions'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/refunds'
    | '/_authenticated/dashboard/rewards'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/campaigns/$slug/back'
    | '/_authenticated/admin/'
    | '/_authenticated/creator/'
    | '/_authenticated/dashboard/'
    | '/campaigns/$slug/'
    | '/_authenticated/admin/campaign-reviews/$campaignId'
    | '/_authenticated/creator/campaigns/new'
    | '/api/public/ai/chat'
    | '/api/public/ai/generate-campaign-summary'
    | '/api/public/hooks/process-notification-outbox'
    | '/api/public/hooks/publish-due-campaigns'
    | '/api/public/hooks/run-payment-reconciliation'
    | '/api/public/hooks/stripe-connect-webhook'
    | '/api/public/hooks/stripe-webhook'
    | '/campaigns/$slug/back/details'
    | '/campaigns/$slug/back/result'
    | '/campaigns/$slug/back/review'
    | '/campaigns/$slug/back/reward'
    | '/_authenticated/admin/campaign-reviews/'
    | '/_authenticated/creator/campaigns/'
    | '/campaigns/$slug/back/'
    | '/_authenticated/admin/campaigns/$campaignId/history'
    | '/_authenticated/creator/campaigns/$campaignId/analytics'
    | '/_authenticated/creator/campaigns/$campaignId/backers'
    | '/_authenticated/creator/campaigns/$campaignId/finance'
    | '/_authenticated/creator/campaigns/$campaignId/overview'
    | '/_authenticated/creator/campaigns/$campaignId/preview'
    | '/_authenticated/creator/campaigns/$campaignId/review'
    | '/_authenticated/creator/campaigns/$campaignId/updates'
    | '/_authenticated/creator/campaigns/$campaignId/edit/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ComplaintsAndAppealsRoute: typeof ComplaintsAndAppealsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CreatorAgreementRoute: typeof CreatorAgreementRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProhibitedCampaignsRoute: typeof ProhibitedCampaignsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CampaignsSlugRoute: typeof CampaignsSlugRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CreatorsUsernameRoute: typeof CreatorsUsernameRoute
  ApiPublicAiChatRoute: typeof ApiPublicAiChatRoute
  ApiPublicAiGenerateCampaignSummaryRoute: typeof ApiPublicAiGenerateCampaignSummaryRoute
  ApiPublicHooksProcessNotificationOutboxRoute: typeof ApiPublicHooksProcessNotificationOutboxRoute
  ApiPublicHooksPublishDueCampaignsRoute: typeof ApiPublicHooksPublishDueCampaignsRoute
  ApiPublicHooksRunPaymentReconciliationRoute: typeof ApiPublicHooksRunPaymentReconciliationRoute
  ApiPublicHooksStripeConnectWebhookRoute: typeof ApiPublicHooksStripeConnectWebhookRoute
  ApiPublicHooksStripeWebhookRoute: typeof ApiPublicHooksStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibited-campaigns': {
      id: '/prohibited-campaigns'
      path: '/prohibited-campaigns'
      fullPath: '/prohibited-campaigns'
      preLoaderRoute: typeof ProhibitedCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-agreement': {
      id: '/creator-agreement'
      path: '/creator-agreement'
      fullPath: '/creator-agreement'
      preLoaderRoute: typeof CreatorAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints-and-appeals': {
      id: '/complaints-and-appeals'
      path: '/complaints-and-appeals'
      fullPath: '/complaints-and-appeals'
      preLoaderRoute: typeof ComplaintsAndAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$username': {
      id: '/creators/$username'
      path: '/creators/$username'
      fullPath: '/creators/$username'
      preLoaderRoute: typeof CreatorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/campaigns/$slug/': {
      id: '/campaigns/$slug/'
      path: '/'
      fullPath: '/campaigns/$slug/'
      preLoaderRoute: typeof CampaignsSlugIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/': {
      id: '/_authenticated/creator/'
      path: '/creator'
      fullPath: '/creator/'
      preLoaderRoute: typeof AuthenticatedCreatorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/campaigns/$slug/back': {
      id: '/campaigns/$slug/back'
      path: '/back'
      fullPath: '/campaigns/$slug/back'
      preLoaderRoute: typeof CampaignsSlugBackRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/dashboard/rewards': {
      id: '/_authenticated/dashboard/rewards'
      path: '/dashboard/rewards'
      fullPath: '/dashboard/rewards'
      preLoaderRoute: typeof AuthenticatedDashboardRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/refunds': {
      id: '/_authenticated/dashboard/refunds'
      path: '/dashboard/refunds'
      fullPath: '/dashboard/refunds'
      preLoaderRoute: typeof AuthenticatedDashboardRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/contributions': {
      id: '/_authenticated/dashboard/contributions'
      path: '/dashboard/contributions'
      fullPath: '/dashboard/contributions'
      preLoaderRoute: typeof AuthenticatedDashboardContributionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/payment-account': {
      id: '/_authenticated/creator/payment-account'
      path: '/creator/payment-account'
      fullPath: '/creator/payment-account'
      preLoaderRoute: typeof AuthenticatedCreatorPaymentAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/campaigns': {
      id: '/_authenticated/creator/campaigns'
      path: '/creator/campaigns'
      fullPath: '/creator/campaigns'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/system-alerts': {
      id: '/_authenticated/admin/system-alerts'
      path: '/system-alerts'
      fullPath: '/admin/system-alerts'
      preLoaderRoute: typeof AuthenticatedAdminSystemAlertsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/campaigns/$slug/back/': {
      id: '/campaigns/$slug/back/'
      path: '/'
      fullPath: '/campaigns/$slug/back/'
      preLoaderRoute: typeof CampaignsSlugBackIndexRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/_authenticated/creator/campaigns/': {
      id: '/_authenticated/creator/campaigns/'
      path: '/'
      fullPath: '/creator/campaigns/'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/admin/campaign-reviews/': {
      id: '/_authenticated/admin/campaign-reviews/'
      path: '/campaign-reviews'
      fullPath: '/admin/campaign-reviews/'
      preLoaderRoute: typeof AuthenticatedAdminCampaignReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/campaigns/$slug/back/reward': {
      id: '/campaigns/$slug/back/reward'
      path: '/reward'
      fullPath: '/campaigns/$slug/back/reward'
      preLoaderRoute: typeof CampaignsSlugBackRewardRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/campaigns/$slug/back/review': {
      id: '/campaigns/$slug/back/review'
      path: '/review'
      fullPath: '/campaigns/$slug/back/review'
      preLoaderRoute: typeof CampaignsSlugBackReviewRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/campaigns/$slug/back/result': {
      id: '/campaigns/$slug/back/result'
      path: '/result'
      fullPath: '/campaigns/$slug/back/result'
      preLoaderRoute: typeof CampaignsSlugBackResultRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/campaigns/$slug/back/details': {
      id: '/campaigns/$slug/back/details'
      path: '/details'
      fullPath: '/campaigns/$slug/back/details'
      preLoaderRoute: typeof CampaignsSlugBackDetailsRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/api/public/hooks/stripe-webhook': {
      id: '/api/public/hooks/stripe-webhook'
      path: '/api/public/hooks/stripe-webhook'
      fullPath: '/api/public/hooks/stripe-webhook'
      preLoaderRoute: typeof ApiPublicHooksStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe-connect-webhook': {
      id: '/api/public/hooks/stripe-connect-webhook'
      path: '/api/public/hooks/stripe-connect-webhook'
      fullPath: '/api/public/hooks/stripe-connect-webhook'
      preLoaderRoute: typeof ApiPublicHooksStripeConnectWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-payment-reconciliation': {
      id: '/api/public/hooks/run-payment-reconciliation'
      path: '/api/public/hooks/run-payment-reconciliation'
      fullPath: '/api/public/hooks/run-payment-reconciliation'
      preLoaderRoute: typeof ApiPublicHooksRunPaymentReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-due-campaigns': {
      id: '/api/public/hooks/publish-due-campaigns'
      path: '/api/public/hooks/publish-due-campaigns'
      fullPath: '/api/public/hooks/publish-due-campaigns'
      preLoaderRoute: typeof ApiPublicHooksPublishDueCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-notification-outbox': {
      id: '/api/public/hooks/process-notification-outbox'
      path: '/api/public/hooks/process-notification-outbox'
      fullPath: '/api/public/hooks/process-notification-outbox'
      preLoaderRoute: typeof ApiPublicHooksProcessNotificationOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/generate-campaign-summary': {
      id: '/api/public/ai/generate-campaign-summary'
      path: '/api/public/ai/generate-campaign-summary'
      fullPath: '/api/public/ai/generate-campaign-summary'
      preLoaderRoute: typeof ApiPublicAiGenerateCampaignSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai/chat': {
      id: '/api/public/ai/chat'
      path: '/api/public/ai/chat'
      fullPath: '/api/public/ai/chat'
      preLoaderRoute: typeof ApiPublicAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/creator/campaigns/new': {
      id: '/_authenticated/creator/campaigns/new'
      path: '/new'
      fullPath: '/creator/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/admin/campaign-reviews/$campaignId': {
      id: '/_authenticated/admin/campaign-reviews/$campaignId'
      path: '/campaign-reviews/$campaignId'
      fullPath: '/admin/campaign-reviews/$campaignId'
      preLoaderRoute: typeof AuthenticatedAdminCampaignReviewsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/updates': {
      id: '/_authenticated/creator/campaigns/$campaignId/updates'
      path: '/$campaignId/updates'
      fullPath: '/creator/campaigns/$campaignId/updates'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/review': {
      id: '/_authenticated/creator/campaigns/$campaignId/review'
      path: '/$campaignId/review'
      fullPath: '/creator/campaigns/$campaignId/review'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdReviewRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/preview': {
      id: '/_authenticated/creator/campaigns/$campaignId/preview'
      path: '/$campaignId/preview'
      fullPath: '/creator/campaigns/$campaignId/preview'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/overview': {
      id: '/_authenticated/creator/campaigns/$campaignId/overview'
      path: '/$campaignId/overview'
      fullPath: '/creator/campaigns/$campaignId/overview'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdOverviewRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/finance': {
      id: '/_authenticated/creator/campaigns/$campaignId/finance'
      path: '/$campaignId/finance'
      fullPath: '/creator/campaigns/$campaignId/finance'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdFinanceRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/backers': {
      id: '/_authenticated/creator/campaigns/$campaignId/backers'
      path: '/$campaignId/backers'
      fullPath: '/creator/campaigns/$campaignId/backers'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdBackersRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/analytics': {
      id: '/_authenticated/creator/campaigns/$campaignId/analytics'
      path: '/$campaignId/analytics'
      fullPath: '/creator/campaigns/$campaignId/analytics'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/admin/campaigns/$campaignId/history': {
      id: '/_authenticated/admin/campaigns/$campaignId/history'
      path: '/campaigns/$campaignId/history'
      fullPath: '/admin/campaigns/$campaignId/history'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsCampaignIdHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/edit/$step': {
      id: '/_authenticated/creator/campaigns/$campaignId/edit/$step'
      path: '/$campaignId/edit/$step'
      fullPath: '/creator/campaigns/$campaignId/edit/$step'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminSystemAlertsRoute: typeof AuthenticatedAdminSystemAlertsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCampaignReviewsCampaignIdRoute: typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  AuthenticatedAdminCampaignReviewsIndexRoute: typeof AuthenticatedAdminCampaignReviewsIndexRoute
  AuthenticatedAdminCampaignsCampaignIdHistoryRoute: typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminSystemAlertsRoute: AuthenticatedAdminSystemAlertsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCampaignReviewsCampaignIdRoute:
    AuthenticatedAdminCampaignReviewsCampaignIdRoute,
  AuthenticatedAdminCampaignReviewsIndexRoute:
    AuthenticatedAdminCampaignReviewsIndexRoute,
  AuthenticatedAdminCampaignsCampaignIdHistoryRoute:
    AuthenticatedAdminCampaignsCampaignIdHistoryRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedCreatorCampaignsRouteChildren {
  AuthenticatedCreatorCampaignsNewRoute: typeof AuthenticatedCreatorCampaignsNewRoute
  AuthenticatedCreatorCampaignsIndexRoute: typeof AuthenticatedCreatorCampaignsIndexRoute
  AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute: typeof AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute
  AuthenticatedCreatorCampaignsCampaignIdBackersRoute: typeof AuthenticatedCreatorCampaignsCampaignIdBackersRoute
  AuthenticatedCreatorCampaignsCampaignIdFinanceRoute: typeof AuthenticatedCreatorCampaignsCampaignIdFinanceRoute
  AuthenticatedCreatorCampaignsCampaignIdOverviewRoute: typeof AuthenticatedCreatorCampaignsCampaignIdOverviewRoute
  AuthenticatedCreatorCampaignsCampaignIdPreviewRoute: typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  AuthenticatedCreatorCampaignsCampaignIdReviewRoute: typeof AuthenticatedCreatorCampaignsCampaignIdReviewRoute
  AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute: typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  AuthenticatedCreatorCampaignsCampaignIdEditStepRoute: typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}

const AuthenticatedCreatorCampaignsRouteChildren: AuthenticatedCreatorCampaignsRouteChildren =
  {
    AuthenticatedCreatorCampaignsNewRoute:
      AuthenticatedCreatorCampaignsNewRoute,
    AuthenticatedCreatorCampaignsIndexRoute:
      AuthenticatedCreatorCampaignsIndexRoute,
    AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute:
      AuthenticatedCreatorCampaignsCampaignIdAnalyticsRoute,
    AuthenticatedCreatorCampaignsCampaignIdBackersRoute:
      AuthenticatedCreatorCampaignsCampaignIdBackersRoute,
    AuthenticatedCreatorCampaignsCampaignIdFinanceRoute:
      AuthenticatedCreatorCampaignsCampaignIdFinanceRoute,
    AuthenticatedCreatorCampaignsCampaignIdOverviewRoute:
      AuthenticatedCreatorCampaignsCampaignIdOverviewRoute,
    AuthenticatedCreatorCampaignsCampaignIdPreviewRoute:
      AuthenticatedCreatorCampaignsCampaignIdPreviewRoute,
    AuthenticatedCreatorCampaignsCampaignIdReviewRoute:
      AuthenticatedCreatorCampaignsCampaignIdReviewRoute,
    AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute:
      AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute,
    AuthenticatedCreatorCampaignsCampaignIdEditStepRoute:
      AuthenticatedCreatorCampaignsCampaignIdEditStepRoute,
  }

const AuthenticatedCreatorCampaignsRouteWithChildren =
  AuthenticatedCreatorCampaignsRoute._addFileChildren(
    AuthenticatedCreatorCampaignsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedCreatorCampaignsRoute: typeof AuthenticatedCreatorCampaignsRouteWithChildren
  AuthenticatedCreatorPaymentAccountRoute: typeof AuthenticatedCreatorPaymentAccountRoute
  AuthenticatedDashboardContributionsRoute: typeof AuthenticatedDashboardContributionsRoute
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardRefundsRoute: typeof AuthenticatedDashboardRefundsRoute
  AuthenticatedDashboardRewardsRoute: typeof AuthenticatedDashboardRewardsRoute
  AuthenticatedCreatorIndexRoute: typeof AuthenticatedCreatorIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedCreatorCampaignsRoute:
    AuthenticatedCreatorCampaignsRouteWithChildren,
  AuthenticatedCreatorPaymentAccountRoute:
    AuthenticatedCreatorPaymentAccountRoute,
  AuthenticatedDashboardContributionsRoute:
    AuthenticatedDashboardContributionsRoute,
  AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
  AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
  AuthenticatedDashboardRefundsRoute: AuthenticatedDashboardRefundsRoute,
  AuthenticatedDashboardRewardsRoute: AuthenticatedDashboardRewardsRoute,
  AuthenticatedCreatorIndexRoute: AuthenticatedCreatorIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CampaignsSlugBackRouteChildren {
  CampaignsSlugBackDetailsRoute: typeof CampaignsSlugBackDetailsRoute
  CampaignsSlugBackResultRoute: typeof CampaignsSlugBackResultRoute
  CampaignsSlugBackReviewRoute: typeof CampaignsSlugBackReviewRoute
  CampaignsSlugBackRewardRoute: typeof CampaignsSlugBackRewardRoute
  CampaignsSlugBackIndexRoute: typeof CampaignsSlugBackIndexRoute
}

const CampaignsSlugBackRouteChildren: CampaignsSlugBackRouteChildren = {
  CampaignsSlugBackDetailsRoute: CampaignsSlugBackDetailsRoute,
  CampaignsSlugBackResultRoute: CampaignsSlugBackResultRoute,
  CampaignsSlugBackReviewRoute: CampaignsSlugBackReviewRoute,
  CampaignsSlugBackRewardRoute: CampaignsSlugBackRewardRoute,
  CampaignsSlugBackIndexRoute: CampaignsSlugBackIndexRoute,
}

const CampaignsSlugBackRouteWithChildren =
  CampaignsSlugBackRoute._addFileChildren(CampaignsSlugBackRouteChildren)

interface CampaignsSlugRouteChildren {
  CampaignsSlugBackRoute: typeof CampaignsSlugBackRouteWithChildren
  CampaignsSlugIndexRoute: typeof CampaignsSlugIndexRoute
}

const CampaignsSlugRouteChildren: CampaignsSlugRouteChildren = {
  CampaignsSlugBackRoute: CampaignsSlugBackRouteWithChildren,
  CampaignsSlugIndexRoute: CampaignsSlugIndexRoute,
}

const CampaignsSlugRouteWithChildren = CampaignsSlugRoute._addFileChildren(
  CampaignsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ComplaintsAndAppealsRoute: ComplaintsAndAppealsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CreatorAgreementRoute: CreatorAgreementRoute,
  DesignSystemRoute: DesignSystemRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProhibitedCampaignsRoute: ProhibitedCampaignsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CampaignsSlugRoute: CampaignsSlugRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CreatorsUsernameRoute: CreatorsUsernameRoute,
  ApiPublicAiChatRoute: ApiPublicAiChatRoute,
  ApiPublicAiGenerateCampaignSummaryRoute:
    ApiPublicAiGenerateCampaignSummaryRoute,
  ApiPublicHooksProcessNotificationOutboxRoute:
    ApiPublicHooksProcessNotificationOutboxRoute,
  ApiPublicHooksPublishDueCampaignsRoute:
    ApiPublicHooksPublishDueCampaignsRoute,
  ApiPublicHooksRunPaymentReconciliationRoute:
    ApiPublicHooksRunPaymentReconciliationRoute,
  ApiPublicHooksStripeConnectWebhookRoute:
    ApiPublicHooksStripeConnectWebhookRoute,
  ApiPublicHooksStripeWebhookRoute: ApiPublicHooksStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
