/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorsUsernameRouteImport } from './routes/creators.$username'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CampaignsSlugBackRouteImport } from './routes/campaigns.$slug.back'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedCreatorCampaignsRouteImport } from './routes/_authenticated/creator.campaigns'
import { Route as CampaignsSlugBackIndexRouteImport } from './routes/campaigns.$slug.back.index'
import { Route as AuthenticatedCreatorCampaignsIndexRouteImport } from './routes/_authenticated/creator.campaigns.index'
import { Route as AuthenticatedAdminCampaignReviewsIndexRouteImport } from './routes/_authenticated/admin.campaign-reviews.index'
import { Route as CampaignsSlugBackRewardRouteImport } from './routes/campaigns.$slug.back.reward'
import { Route as CampaignsSlugBackDetailsRouteImport } from './routes/campaigns.$slug.back.details'
import { Route as ApiPublicHooksPublishDueCampaignsRouteImport } from './routes/api/public/hooks/publish-due-campaigns'
import { Route as AuthenticatedCreatorCampaignsNewRouteImport } from './routes/_authenticated/creator.campaigns.new'
import { Route as AuthenticatedAdminCampaignReviewsCampaignIdRouteImport } from './routes/_authenticated/admin.campaign-reviews.$campaignId'
import { Route as AuthenticatedCreatorCampaignsCampaignIdUpdatesRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.updates'
import { Route as AuthenticatedCreatorCampaignsCampaignIdPreviewRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.preview'
import { Route as AuthenticatedAdminCampaignsCampaignIdHistoryRouteImport } from './routes/_authenticated/admin.campaigns.$campaignId.history'
import { Route as AuthenticatedCreatorCampaignsCampaignIdEditStepRouteImport } from './routes/_authenticated/creator.campaigns.$campaignId.edit.$step'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsUsernameRoute = CreatorsUsernameRouteImport.update({
  id: '/creators/$username',
  path: '/creators/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CampaignsSlugBackRoute = CampaignsSlugBackRouteImport.update({
  id: '/back',
  path: '/back',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedCreatorCampaignsRoute =
  AuthenticatedCreatorCampaignsRouteImport.update({
    id: '/creator/campaigns',
    path: '/creator/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CampaignsSlugBackIndexRoute = CampaignsSlugBackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugBackRoute,
} as any)
const AuthenticatedCreatorCampaignsIndexRoute =
  AuthenticatedCreatorCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedAdminCampaignReviewsIndexRoute =
  AuthenticatedAdminCampaignReviewsIndexRouteImport.update({
    id: '/campaign-reviews/',
    path: '/campaign-reviews/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CampaignsSlugBackRewardRoute = CampaignsSlugBackRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => CampaignsSlugBackRoute,
} as any)
const CampaignsSlugBackDetailsRoute =
  CampaignsSlugBackDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => CampaignsSlugBackRoute,
  } as any)
const ApiPublicHooksPublishDueCampaignsRoute =
  ApiPublicHooksPublishDueCampaignsRouteImport.update({
    id: '/api/public/hooks/publish-due-campaigns',
    path: '/api/public/hooks/publish-due-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCreatorCampaignsNewRoute =
  AuthenticatedCreatorCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedAdminCampaignReviewsCampaignIdRoute =
  AuthenticatedAdminCampaignReviewsCampaignIdRouteImport.update({
    id: '/campaign-reviews/$campaignId',
    path: '/campaign-reviews/$campaignId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute =
  AuthenticatedCreatorCampaignsCampaignIdUpdatesRouteImport.update({
    id: '/$campaignId/updates',
    path: '/$campaignId/updates',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdPreviewRoute =
  AuthenticatedCreatorCampaignsCampaignIdPreviewRouteImport.update({
    id: '/$campaignId/preview',
    path: '/$campaignId/preview',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)
const AuthenticatedAdminCampaignsCampaignIdHistoryRoute =
  AuthenticatedAdminCampaignsCampaignIdHistoryRouteImport.update({
    id: '/campaigns/$campaignId/history',
    path: '/campaigns/$campaignId/history',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCreatorCampaignsCampaignIdEditStepRoute =
  AuthenticatedCreatorCampaignsCampaignIdEditStepRouteImport.update({
    id: '/$campaignId/edit/$step',
    path: '/$campaignId/edit/$step',
    getParentRoute: () => AuthenticatedCreatorCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/creator/campaigns': typeof AuthenticatedCreatorCampaignsRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/campaigns/$slug/back': typeof CampaignsSlugBackRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/campaign-reviews/$campaignId': typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  '/creator/campaigns/new': typeof AuthenticatedCreatorCampaignsNewRoute
  '/api/public/hooks/publish-due-campaigns': typeof ApiPublicHooksPublishDueCampaignsRoute
  '/campaigns/$slug/back/details': typeof CampaignsSlugBackDetailsRoute
  '/campaigns/$slug/back/reward': typeof CampaignsSlugBackRewardRoute
  '/admin/campaign-reviews/': typeof AuthenticatedAdminCampaignReviewsIndexRoute
  '/creator/campaigns/': typeof AuthenticatedCreatorCampaignsIndexRoute
  '/campaigns/$slug/back/': typeof CampaignsSlugBackIndexRoute
  '/admin/campaigns/$campaignId/history': typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
  '/creator/campaigns/$campaignId/preview': typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  '/creator/campaigns/$campaignId/updates': typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  '/creator/campaigns/$campaignId/edit/$step': typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/campaign-reviews/$campaignId': typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  '/creator/campaigns/new': typeof AuthenticatedCreatorCampaignsNewRoute
  '/api/public/hooks/publish-due-campaigns': typeof ApiPublicHooksPublishDueCampaignsRoute
  '/campaigns/$slug/back/details': typeof CampaignsSlugBackDetailsRoute
  '/campaigns/$slug/back/reward': typeof CampaignsSlugBackRewardRoute
  '/admin/campaign-reviews': typeof AuthenticatedAdminCampaignReviewsIndexRoute
  '/creator/campaigns': typeof AuthenticatedCreatorCampaignsIndexRoute
  '/campaigns/$slug/back': typeof CampaignsSlugBackIndexRoute
  '/admin/campaigns/$campaignId/history': typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
  '/creator/campaigns/$campaignId/preview': typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  '/creator/campaigns/$campaignId/updates': typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  '/creator/campaigns/$campaignId/edit/$step': typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/design-system': typeof DesignSystemRoute
  '/discover': typeof DiscoverRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/_authenticated/creator/campaigns': typeof AuthenticatedCreatorCampaignsRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/campaigns/$slug/back': typeof CampaignsSlugBackRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/campaign-reviews/$campaignId': typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  '/_authenticated/creator/campaigns/new': typeof AuthenticatedCreatorCampaignsNewRoute
  '/api/public/hooks/publish-due-campaigns': typeof ApiPublicHooksPublishDueCampaignsRoute
  '/campaigns/$slug/back/details': typeof CampaignsSlugBackDetailsRoute
  '/campaigns/$slug/back/reward': typeof CampaignsSlugBackRewardRoute
  '/_authenticated/admin/campaign-reviews/': typeof AuthenticatedAdminCampaignReviewsIndexRoute
  '/_authenticated/creator/campaigns/': typeof AuthenticatedCreatorCampaignsIndexRoute
  '/campaigns/$slug/back/': typeof CampaignsSlugBackIndexRoute
  '/_authenticated/admin/campaigns/$campaignId/history': typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
  '/_authenticated/creator/campaigns/$campaignId/preview': typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  '/_authenticated/creator/campaigns/$campaignId/updates': typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  '/_authenticated/creator/campaigns/$campaignId/edit/$step': typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/design-system'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/unauthorized'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/campaigns/$slug'
    | '/categories/$slug'
    | '/creators/$username'
    | '/creator/campaigns'
    | '/settings/account'
    | '/settings/profile'
    | '/campaigns/$slug/back'
    | '/admin/'
    | '/admin/campaign-reviews/$campaignId'
    | '/creator/campaigns/new'
    | '/api/public/hooks/publish-due-campaigns'
    | '/campaigns/$slug/back/details'
    | '/campaigns/$slug/back/reward'
    | '/admin/campaign-reviews/'
    | '/creator/campaigns/'
    | '/campaigns/$slug/back/'
    | '/admin/campaigns/$campaignId/history'
    | '/creator/campaigns/$campaignId/preview'
    | '/creator/campaigns/$campaignId/updates'
    | '/creator/campaigns/$campaignId/edit/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/design-system'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/unauthorized'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/campaigns/$slug'
    | '/categories/$slug'
    | '/creators/$username'
    | '/settings/account'
    | '/settings/profile'
    | '/admin'
    | '/admin/campaign-reviews/$campaignId'
    | '/creator/campaigns/new'
    | '/api/public/hooks/publish-due-campaigns'
    | '/campaigns/$slug/back/details'
    | '/campaigns/$slug/back/reward'
    | '/admin/campaign-reviews'
    | '/creator/campaigns'
    | '/campaigns/$slug/back'
    | '/admin/campaigns/$campaignId/history'
    | '/creator/campaigns/$campaignId/preview'
    | '/creator/campaigns/$campaignId/updates'
    | '/creator/campaigns/$campaignId/edit/$step'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/design-system'
    | '/discover'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/campaigns/$slug'
    | '/categories/$slug'
    | '/creators/$username'
    | '/_authenticated/creator/campaigns'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/profile'
    | '/campaigns/$slug/back'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/campaign-reviews/$campaignId'
    | '/_authenticated/creator/campaigns/new'
    | '/api/public/hooks/publish-due-campaigns'
    | '/campaigns/$slug/back/details'
    | '/campaigns/$slug/back/reward'
    | '/_authenticated/admin/campaign-reviews/'
    | '/_authenticated/creator/campaigns/'
    | '/campaigns/$slug/back/'
    | '/_authenticated/admin/campaigns/$campaignId/history'
    | '/_authenticated/creator/campaigns/$campaignId/preview'
    | '/_authenticated/creator/campaigns/$campaignId/updates'
    | '/_authenticated/creator/campaigns/$campaignId/edit/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DiscoverRoute: typeof DiscoverRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CampaignsSlugRoute: typeof CampaignsSlugRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CreatorsUsernameRoute: typeof CreatorsUsernameRoute
  ApiPublicHooksPublishDueCampaignsRoute: typeof ApiPublicHooksPublishDueCampaignsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$username': {
      id: '/creators/$username'
      path: '/creators/$username'
      fullPath: '/creators/$username'
      preLoaderRoute: typeof CreatorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/campaigns/$slug/back': {
      id: '/campaigns/$slug/back'
      path: '/back'
      fullPath: '/campaigns/$slug/back'
      preLoaderRoute: typeof CampaignsSlugBackRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/creator/campaigns': {
      id: '/_authenticated/creator/campaigns'
      path: '/creator/campaigns'
      fullPath: '/creator/campaigns'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/campaigns/$slug/back/': {
      id: '/campaigns/$slug/back/'
      path: '/'
      fullPath: '/campaigns/$slug/back/'
      preLoaderRoute: typeof CampaignsSlugBackIndexRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/_authenticated/creator/campaigns/': {
      id: '/_authenticated/creator/campaigns/'
      path: '/'
      fullPath: '/creator/campaigns/'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/admin/campaign-reviews/': {
      id: '/_authenticated/admin/campaign-reviews/'
      path: '/campaign-reviews'
      fullPath: '/admin/campaign-reviews/'
      preLoaderRoute: typeof AuthenticatedAdminCampaignReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/campaigns/$slug/back/reward': {
      id: '/campaigns/$slug/back/reward'
      path: '/reward'
      fullPath: '/campaigns/$slug/back/reward'
      preLoaderRoute: typeof CampaignsSlugBackRewardRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/campaigns/$slug/back/details': {
      id: '/campaigns/$slug/back/details'
      path: '/details'
      fullPath: '/campaigns/$slug/back/details'
      preLoaderRoute: typeof CampaignsSlugBackDetailsRouteImport
      parentRoute: typeof CampaignsSlugBackRoute
    }
    '/api/public/hooks/publish-due-campaigns': {
      id: '/api/public/hooks/publish-due-campaigns'
      path: '/api/public/hooks/publish-due-campaigns'
      fullPath: '/api/public/hooks/publish-due-campaigns'
      preLoaderRoute: typeof ApiPublicHooksPublishDueCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/creator/campaigns/new': {
      id: '/_authenticated/creator/campaigns/new'
      path: '/new'
      fullPath: '/creator/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/admin/campaign-reviews/$campaignId': {
      id: '/_authenticated/admin/campaign-reviews/$campaignId'
      path: '/campaign-reviews/$campaignId'
      fullPath: '/admin/campaign-reviews/$campaignId'
      preLoaderRoute: typeof AuthenticatedAdminCampaignReviewsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/updates': {
      id: '/_authenticated/creator/campaigns/$campaignId/updates'
      path: '/$campaignId/updates'
      fullPath: '/creator/campaigns/$campaignId/updates'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/preview': {
      id: '/_authenticated/creator/campaigns/$campaignId/preview'
      path: '/$campaignId/preview'
      fullPath: '/creator/campaigns/$campaignId/preview'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
    '/_authenticated/admin/campaigns/$campaignId/history': {
      id: '/_authenticated/admin/campaigns/$campaignId/history'
      path: '/campaigns/$campaignId/history'
      fullPath: '/admin/campaigns/$campaignId/history'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsCampaignIdHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/creator/campaigns/$campaignId/edit/$step': {
      id: '/_authenticated/creator/campaigns/$campaignId/edit/$step'
      path: '/$campaignId/edit/$step'
      fullPath: '/creator/campaigns/$campaignId/edit/$step'
      preLoaderRoute: typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRouteImport
      parentRoute: typeof AuthenticatedCreatorCampaignsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCampaignReviewsCampaignIdRoute: typeof AuthenticatedAdminCampaignReviewsCampaignIdRoute
  AuthenticatedAdminCampaignReviewsIndexRoute: typeof AuthenticatedAdminCampaignReviewsIndexRoute
  AuthenticatedAdminCampaignsCampaignIdHistoryRoute: typeof AuthenticatedAdminCampaignsCampaignIdHistoryRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCampaignReviewsCampaignIdRoute:
    AuthenticatedAdminCampaignReviewsCampaignIdRoute,
  AuthenticatedAdminCampaignReviewsIndexRoute:
    AuthenticatedAdminCampaignReviewsIndexRoute,
  AuthenticatedAdminCampaignsCampaignIdHistoryRoute:
    AuthenticatedAdminCampaignsCampaignIdHistoryRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedCreatorCampaignsRouteChildren {
  AuthenticatedCreatorCampaignsNewRoute: typeof AuthenticatedCreatorCampaignsNewRoute
  AuthenticatedCreatorCampaignsIndexRoute: typeof AuthenticatedCreatorCampaignsIndexRoute
  AuthenticatedCreatorCampaignsCampaignIdPreviewRoute: typeof AuthenticatedCreatorCampaignsCampaignIdPreviewRoute
  AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute: typeof AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute
  AuthenticatedCreatorCampaignsCampaignIdEditStepRoute: typeof AuthenticatedCreatorCampaignsCampaignIdEditStepRoute
}

const AuthenticatedCreatorCampaignsRouteChildren: AuthenticatedCreatorCampaignsRouteChildren =
  {
    AuthenticatedCreatorCampaignsNewRoute:
      AuthenticatedCreatorCampaignsNewRoute,
    AuthenticatedCreatorCampaignsIndexRoute:
      AuthenticatedCreatorCampaignsIndexRoute,
    AuthenticatedCreatorCampaignsCampaignIdPreviewRoute:
      AuthenticatedCreatorCampaignsCampaignIdPreviewRoute,
    AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute:
      AuthenticatedCreatorCampaignsCampaignIdUpdatesRoute,
    AuthenticatedCreatorCampaignsCampaignIdEditStepRoute:
      AuthenticatedCreatorCampaignsCampaignIdEditStepRoute,
  }

const AuthenticatedCreatorCampaignsRouteWithChildren =
  AuthenticatedCreatorCampaignsRoute._addFileChildren(
    AuthenticatedCreatorCampaignsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedCreatorCampaignsRoute: typeof AuthenticatedCreatorCampaignsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedCreatorCampaignsRoute:
    AuthenticatedCreatorCampaignsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CampaignsSlugBackRouteChildren {
  CampaignsSlugBackDetailsRoute: typeof CampaignsSlugBackDetailsRoute
  CampaignsSlugBackRewardRoute: typeof CampaignsSlugBackRewardRoute
  CampaignsSlugBackIndexRoute: typeof CampaignsSlugBackIndexRoute
}

const CampaignsSlugBackRouteChildren: CampaignsSlugBackRouteChildren = {
  CampaignsSlugBackDetailsRoute: CampaignsSlugBackDetailsRoute,
  CampaignsSlugBackRewardRoute: CampaignsSlugBackRewardRoute,
  CampaignsSlugBackIndexRoute: CampaignsSlugBackIndexRoute,
}

const CampaignsSlugBackRouteWithChildren =
  CampaignsSlugBackRoute._addFileChildren(CampaignsSlugBackRouteChildren)

interface CampaignsSlugRouteChildren {
  CampaignsSlugBackRoute: typeof CampaignsSlugBackRouteWithChildren
}

const CampaignsSlugRouteChildren: CampaignsSlugRouteChildren = {
  CampaignsSlugBackRoute: CampaignsSlugBackRouteWithChildren,
}

const CampaignsSlugRouteWithChildren = CampaignsSlugRoute._addFileChildren(
  CampaignsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  DesignSystemRoute: DesignSystemRoute,
  DiscoverRoute: DiscoverRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CampaignsSlugRoute: CampaignsSlugRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CreatorsUsernameRoute: CreatorsUsernameRoute,
  ApiPublicHooksPublishDueCampaignsRoute:
    ApiPublicHooksPublishDueCampaignsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
